### ISSUE TITLE
JST XH male vs. female

### ISSUE THREAD

**Issue by LubosD** [uncle-yura/esphome-midea-ac#1]
Hi,

the JST XH connectors are a bit confusing when it comes to gender. Your text mentions that the ESP side should have a female connector, but the picture then shows a male connector.

[This image](https://www.pcboard.ca/image/cache/catalog/products/connectors/jst/jst-xh-2-3-4-5-6-cable-set-800x800.jpg) should make it clear. Unless I got confused as well, I think the README should say:

> So you either need a Type-A USB male connector or JST-XH **male** connector to connect the ESP-01.

**Comment by uncle-yura** [comment]
This is a bit of a confusing question, but I think you're using the wrong image. In the documentation for the connector, there are no concepts of male or female, they are called a header and a housing with contacts, so usually a header is a male (plug), and a housing is a female (socket).
